// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyV-EAEGs3LbV0hIEC2tsafYL-S_JL5o8',
    appId: '1:824831970659:web:f8160787c35d97987f5756',
    messagingSenderId: '824831970659',
    projectId: 'todo-8917c',
    authDomain: 'todo-8917c.firebaseapp.com',
    storageBucket: 'todo-8917c.firebasestorage.app',
    measurementId: 'G-9HLXY4C1ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1u4WdGeHriulzctDFg2BQ0DwYUN3951M',
    appId: '1:824831970659:android:3914fcc001a738847f5756',
    messagingSenderId: '824831970659',
    projectId: 'todo-8917c',
    storageBucket: 'todo-8917c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiAsdOZZIzFxvlrXy4X1qA8q3njuEBn6k',
    appId: '1:824831970659:ios:c8914265a45eaf407f5756',
    messagingSenderId: '824831970659',
    projectId: 'todo-8917c',
    storageBucket: 'todo-8917c.firebasestorage.app',
    iosBundleId: 'com.ishita.gameSnake',
  );
}
